# Generated by Django 5.1.1 on 2024-10-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='randomized',
            field=models.BooleanField(default=False),
        ),
    ]
